project_id = "bookshelf-322313"
instance_network = "bookshelf-vpc-network"
region = "europe-west3"
startup_script = "startup-script.sh"
db_user = "mainuser"
gce_instance_type = "e2-medium"
instance_network_tag = "in-tag"
db_pswd = "Fb9saKDe8rE9gBjb"
db_user_pswd = "Fb9saKDe8rE9gBjb"
sql_region = "europe-west3"
service_account_for_instance = "terraform"
image_bucket_name = "terraform-state-august2021"
bucket_location = "EU"
destroy_policy = "true"


